<?php

declare(strict_types=1);
namespace GreatMarketrealmCompanion\Modules\DungeonMaster\Controllers;
use GreatMarketrealmCompanion\Core\Http\RedirectResponse;use GreatMarketrealmCompanion\Core\Http\ResponseFactory;use GreatMarketrealmCompanion\Core\Session\FlashStore;use GreatMarketrealmCompanion\Core\View\View;use GreatMarketrealmCompanion\Core\View\ViewFactory;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Campaign;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\EvidenceRecord;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Location;use GreatMarketrealmCompanion\Modules\DungeonMaster\Models\Persona;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\CampaignRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\ConspiracyBoardRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\EvidenceRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\LocationRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Repositories\PersonaRepository;use GreatMarketrealmCompanion\Modules\DungeonMaster\Services\DungeonMasterAccess;use RuntimeException;
defined('ABSPATH') || exit;
final class ConspiracyBoardController
{
 public function __construct(private CampaignRepository $campaigns,private ConspiracyBoardRepository $board,private LocationRepository $locations,private PersonaRepository $personae,private EvidenceRepository $evidence,private DungeonMasterAccess $access,private ViewFactory $views,private ResponseFactory $responses,private FlashStore $flash){}
 public function index(string $id):string{$campaign=$this->campaign($id);[$pins,$connections]=$this->graph($campaign);return $this->views->render(View::make('dungeonmaster.conspiracy-board.index',['campaign'=>$campaign,'pins'=>$pins,'connections'=>$connections,'positions'=>$this->board->positions($campaign),'annotations'=>$this->board->annotations($campaign),'flash'=>['success'=>$this->flash->get('success'),'error'=>$this->flash->get('error')]]));}
 public function save(string $id):RedirectResponse{$campaign=$this->campaign($id);if($campaign->isArchived()){throw new RuntimeException('Archived campaigns have a read-only Conspiracy Board.');}$raw=isset($_POST['positions'])?wp_unslash((string)$_POST['positions']):'{}';$decoded=json_decode($raw,true);if(!is_array($decoded)){throw new RuntimeException('The board positions could not be read.');}[$pins]=$this->graph($campaign);$allowed=array_fill_keys(array_column($pins,'key'),true);$positions=[];foreach($decoded as $key=>$value){if(isset($allowed[$key])&&is_array($value)){$positions[$key]=['x'=>(float)($value['x']??0),'y'=>(float)($value['y']??0)];}}$this->board->savePositions($campaign,$positions);$rawAnnotations=isset($_POST['annotations'])?wp_unslash((string)$_POST['annotations']):'[]';$annotations=json_decode($rawAnnotations,true);$this->board->saveAnnotations($campaign,is_array($annotations)?$annotations:[]);$this->flash->success('The strings, pins and suspicious cheese have been left exactly where you put them.');return $this->responses->redirect($this->url($campaign->id()));}
 private function campaign(string $id):Campaign{if(!$this->access->allows()){status_header(403);throw new RuntimeException('The Conspiracy Board is sealed to Dungeon Masters.');}$campaign=$this->campaigns->findForOwner($id,get_current_user_id());if(!$campaign instanceof Campaign){throw new RuntimeException('Campaign not found in this Dungeon Master’s Register.');}return $campaign;}
 /** @return array{0:list<array<string,string>>,1:list<array{from:string,to:string}>} */
 private function graph(Campaign $campaign):array{$pins=[];$edges=[];$seen=[];$add=function(string $type,string $id,string $name,string $label,string $summary,string $route)use(&$pins,&$seen):string{$key=$type.'-'.$id;$seen[$key]=true;$pins[]=['key'=>$key,'type'=>$type,'id'=>$id,'name'=>$name,'label'=>$label,'summary'=>$summary,'route'=>$route];return $key;};
  foreach($this->locations->allForCampaign($campaign) as $r){if($r->isArchived())continue;$key=$add('location',$r->id(),$r->name(),$r->typeLabel(),$r->summary(),$this->recordUrl($campaign,'locations',$r->id()));if($r->parentId()!=='')$edges[]=['from'=>$key,'to'=>'location-'.$r->parentId()];}
  $personaTypes=[];foreach($this->personae->allForCampaign($campaign) as $r){if($r->isArchived())continue;$personaTypes[$r->id()]=$r->isFaction()?'faction':'person';$key=$add($personaTypes[$r->id()],$r->id(),$r->name(),$r->kindLabel(),$r->summary(),$this->recordUrl($campaign,'personae',$r->id()));if($r->factionId()!=='')$edges[]=['from'=>$key,'to'=>'faction-'.$r->factionId()];}
  foreach($this->evidence->allForCampaign($campaign) as $r){if($r->isArchived())continue;$type=$r->isThread()?'thread':'evidence';$key=$add($type,$r->id(),$r->name(),$r->typeLabel(),$r->summary(),$this->recordUrl($campaign,'evidence',$r->id()));foreach($r->threadIds() as $v)$edges[]=['from'=>$key,'to'=>'thread-'.$v];foreach($r->locationIds() as $v)$edges[]=['from'=>$key,'to'=>'location-'.$v];foreach($r->personaIds() as $v){$edges[]=['from'=>$key,'to'=>($personaTypes[$v]??'person').'-'.$v];}}
  $edges=array_values(array_filter($edges,fn($e)=>isset($seen[$e['from']],$seen[$e['to']])));return [$pins,$edges];}
 private function recordUrl(Campaign $campaign,string $register,string $id):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaign->id().'/'.$register.'/'.$id,home_url('/companion/'));}private function url(string $campaignId):string{return add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaignId.'/conspiracy-board',home_url('/companion/'));}
}
