<?php defined('ABSPATH') || exit;$base=home_url('/companion/');$root='dungeon-master/campaigns/'.$campaign->id().'/conspiracy-board';$defaults=['location'=>[10,12],'person'=>[38,10],'faction'=>[68,12],'evidence'=>[18,55],'thread'=>[62,55]]; ?>
<section class="gmrc-conspiracy" data-gmrc-conspiracy-board data-board-readonly="<?php echo $campaign->isArchived()?'1':'0'; ?>">
 <header class="gmrc-conspiracy__hero"><div><p class="gmrc-dm-desk__eyebrow">Keeper’s Workshop · <?php echo esc_html($campaign->name()); ?></p><h1>The Conspiracy Board</h1><p>Every record card stays canonical. Board notes, labels and loose pins belong only to this investigation.</p></div><a class="gmrc-conspiracy__return" href="<?php echo esc_url(add_query_arg('gmrc_route','dungeon-master/campaigns/'.$campaign->id(),$base)); ?>">Campaign Command Centre</a></header>
 <?php if(!empty($flash['success'])):?><p class="gmrc-conspiracy__notice" role="status"><?php echo esc_html($flash['success']); ?></p><?php endif; ?>
 <nav class="gmrc-conspiracy__legend" aria-label="Board legend"><span>🗺️ Locations</span><span>👤 People</span><span>🎭 Factions</span><span>🔎 Evidence</span><span>🧵 Threads</span><strong><?php echo count($pins); ?> records · <?php echo count($annotations); ?> board pins · <?php echo count($connections); ?> strings</strong></nav>
 <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="gmrc-conspiracy__form"><input type="hidden" name="action" value="gmrc_app_request"><input type="hidden" name="gmrc_route" value="<?php echo esc_attr($root); ?>"><input type="hidden" name="_method" value="POST"><input type="hidden" name="gmrc_nonce" value="<?php echo esc_attr(wp_create_nonce('gmrc_dm_conspiracy_board_'.$campaign->id())); ?>"><input type="hidden" name="positions" value="{}" data-gmrc-board-positions><input type="hidden" name="annotations" value="<?php echo esc_attr(wp_json_encode($annotations)); ?>" data-gmrc-board-annotations>
 <div class="gmrc-conspiracy__board" data-gmrc-board-canvas data-connections="<?php echo esc_attr(wp_json_encode($connections)); ?>"><svg class="gmrc-conspiracy__strings" aria-hidden="true" data-gmrc-board-strings></svg>
 <?php $typeIndex=[];foreach($pins as $pin):$i=$typeIndex[$pin['type']]??0;$typeIndex[$pin['type']]=$i+1;$fallback=$defaults[$pin['type']]??[10,10];$pos=$positions[$pin['key']]??['x'=>min(84,$fallback[0]+(($i%3)*8)),'y'=>min(82,$fallback[1]+(intdiv($i,3)*15))]; ?>
  <article class="gmrc-conspiracy-pin gmrc-conspiracy-pin--<?php echo esc_attr($pin['type']); ?>" data-pin-key="<?php echo esc_attr($pin['key']); ?>" style="left:<?php echo esc_attr((string)$pos['x']); ?>%;top:<?php echo esc_attr((string)$pos['y']); ?>%;"><button type="button" class="gmrc-conspiracy-pin__tack" aria-label="Move <?php echo esc_attr($pin['name']); ?>">●</button><p><?php echo esc_html($pin['label']); ?></p><h2><?php echo esc_html($pin['name']); ?></h2><?php if($pin['summary']!==''):?><small><?php echo esc_html($pin['summary']); ?></small><?php endif;?><a href="<?php echo esc_url($pin['route']); ?>">Open record →</a></article>
 <?php endforeach; ?>
 <?php foreach($annotations as $annotation): ?><article class="gmrc-board-annotation gmrc-board-annotation--<?php echo esc_attr($annotation['type']); ?>" data-board-annotation data-annotation-id="<?php echo esc_attr($annotation['id']); ?>" data-annotation-type="<?php echo esc_attr($annotation['type']); ?>" style="left:<?php echo esc_attr((string)$annotation['x']); ?>%;top:<?php echo esc_attr((string)$annotation['y']); ?>%;"><button type="button" class="gmrc-board-annotation__tack" aria-label="Move board item">●</button><?php if($annotation['type']!=='pin'):?><div><?php echo nl2br(esc_html($annotation['text'])); ?></div><?php endif;?></article><?php endforeach; ?>
 <div class="gmrc-board-context" data-gmrc-board-context hidden><button type="button" data-board-add="note">📝 Add Note</button><button type="button" data-board-add="label">🏷️ Add Label</button><button type="button" data-board-add="pin">📌 Add Pin</button></div>
 </div>
 <?php if(!$campaign->isArchived()):?><div class="gmrc-conspiracy__actions"><p>Drag by a tack. Right-click empty cork to add a note, label or loose pin. Strings deliberately hang with a little Keeper-grade slack.</p><button type="submit">Save Board Layout</button></div><?php endif;?></form>
</section>
